# Generated by Django 5.1.5 on 2026-09-26 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text="Stable identifier used by the code that fires it, e.g. 'login'.", max_length=64, unique=True)),
                ('name', models.CharField(help_text='Shown in the admin table.', max_length=120)),
                ('description', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('event', 'Event'), ('inactivity', 'Inactivity window')], default='event', help_text='Event = fired by application code. Inactivity window = fired by the scheduled scanner.', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Extra settings. Inactivity triggers use {"days": 1}.')),
                ('is_active', models.BooleanField(default=True, help_text='Master switch for the whole trigger.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'trigger',
                'verbose_name_plural': 'triggers',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('webpush', 'Raw Web Push (VAPID)'), ('onesignal', 'OneSignal')], default='webpush', max_length=20)),
                ('endpoint', models.URLField(max_length=500)),
                ('p256dh', models.CharField(blank=True, max_length=255)),
                ('auth', models.CharField(blank=True, max_length=255)),
                ('onesignal_subscription_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'push subscription',
                'verbose_name_plural': 'push subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('webpush', 'Web Push')], max_length=20)),
                ('title', models.CharField(blank=True, help_text='Web Push notification title.', max_length=200)),
                ('subject', models.CharField(blank=True, help_text='Email subject line.', max_length=200)),
                ('body', models.TextField(blank=True, help_text='Message copy. Use {{ placeholders }} - see variables below.')),
                ('provider_template_name', models.CharField(blank=True, help_text='WhatsApp only: the approved template name in Meta. Leave blank to send the body as free-form text (sandbox only).', max_length=120)),
                ('provider_language', models.CharField(blank=True, help_text='WhatsApp only, e.g. en_US.', max_length=16)),
                ('is_enabled', models.BooleanField(default=True, help_text='Per-channel on/off toggle.')),
                ('variables', models.JSONField(blank=True, default=list, editable=False, help_text='Auto-detected placeholders used by this template.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='notifications.trigger')),
            ],
            options={
                'verbose_name': 'template',
                'verbose_name_plural': 'templates',
                'ordering': ['trigger__order', 'trigger__name', 'channel'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('webpush', 'Web Push')], max_length=20)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('simulated', 'Simulated (sandbox)'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='simulated', max_length=20)),
                ('destination', models.CharField(blank=True, help_text='Where it went (masked).', max_length=300)),
                ('rendered_title', models.CharField(blank=True, max_length=200)),
                ('rendered_subject', models.CharField(blank=True, max_length=200)),
                ('rendered_body', models.TextField(blank=True)),
                ('provider', models.CharField(blank=True, max_length=40)),
                ('provider_message_id', models.CharField(blank=True, max_length=200)),
                ('error', models.TextField(blank=True)),
                ('is_test', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='notifications.template')),
                ('trigger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='notifications.trigger')),
            ],
            options={
                'verbose_name': 'notification log',
                'verbose_name_plural': 'notification logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_e164', models.CharField(blank=True, help_text='WhatsApp number in E.164 format, e.g. +919876543210.', max_length=24)),
                ('last_seen_at', models.DateTimeField(blank=True, help_text='Drives the inactivity triggers.', null=True)),
                ('whatsapp_opt_in', models.BooleanField(default=True)),
                ('email_opt_in', models.BooleanField(default=True)),
                ('webpush_opt_in', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='template',
            constraint=models.UniqueConstraint(fields=('trigger', 'channel'), name='unique_template_per_trigger_channel'),
        ),
    ]
