# Generated by Django 5.1.5 on 2026-09-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='provider_status',
            field=models.CharField(choices=[('not_submitted', 'Not submitted to Meta'), ('draft', 'Draft created in Meta'), ('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_submitted', help_text="WhatsApp only: where this template is in Meta's approval flow. The sandbox cannot submit templates, so this is recorded by hand.", max_length=20),
        ),
        migrations.AddField(
            model_name='template',
            name='provider_status_note',
            field=models.CharField(blank=True, help_text='Why Meta rejected it, or any note about the submission.', max_length=300),
        ),
        migrations.AddField(
            model_name='template',
            name='provider_submitted_at',
            field=models.DateTimeField(blank=True, editable=False, help_text="Set automatically the first time the status leaves 'not submitted'.", null=True),
        ),
    ]
